[package]
name = "aap-policy"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
aap-types.workspace = true
serde.workspace = true
url.workspace = true
http.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
