[package]
name = "aap-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
aap-types.workspace = true
bytes.workspace = true
http.workspace = true
http-body.workspace = true
http-body-util.workspace = true
httparse.workspace = true
hyper = { workspace = true, features = ["client", "http1"] }
hyper-util.workspace = true
tokio = { workspace = true, features = ["rt", "net", "time", "io-util", "sync", "macros"] }
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "io-util", "sync", "test-util"] }

[target.'cfg(target_os = "linux")'.dev-dependencies]
rustix.workspace = true

[[example]]
name = "confinement-agent"
path = "examples/confinement_agent/main.rs"

[lints]
workspace = true
